### ISSUE TITLE
Comp: Input field

### ISSUE THREAD

**Issue by gintaresaali** [FUKA-INNOVATIONS/Safeye#16]
- [ ] Create modifier
- [ ] Create View Component

**Comment by FUKA-INNOVATIONS** [comment]
Where should we handle the state?
1. Inside the component OR 
2. Where ever the component is used

Question: What impacts does both situation have on UI re creation,




import SwiftUI

struct InputFieldComponent: View {
    @State var title: String
    @State var text: String

        var body: some View {
            VStack(alignment: .leading) {
                Text(title)
                TextField(title, text: $text)
            }
            .modifier(inputFieldModifier())
        }
}


struct InputFieldComponent_Previews: PreviewProvider {
    static var previews: some View {
        InputFieldComponent(title: "Email address", text: "ff")
    }
}

**Comment by FUKA-INNOVATIONS** [comment]
Lets try to get afew minutes of Juhas time to get his view/advice.
