### ISSUE TITLE
Comp: Alert box

### ISSUE THREAD

**Issue by gintaresaali** [FUKA-INNOVATIONS/Safeye#21]

**Comment by FUKA-INNOVATIONS** [comment]
I think there is no need for a separate alert component at this stage since swift is providing a modifier 
What are your thoughts? Maybe we will come back to this later incase we want to create a custom alert box ?

**Comment by leinonenko** [comment]
Custom component is ready: But it´s functionality with confirmation button implemented only for panic mode for now
