### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by gintaresaali** [FUKA-INNOVATIONS/Safeye#26]
Research: Multiple languages through localization

**Comment by Ali-k-fahad** [comment]
[Support Multilanguage (Localization) In iOS Swift](https://www.c-sharpcorner.com/article/support-multilanguage-localization-in-ios-swift/
)
- Press on Safeye > info > localisations > add languages. 
- Now, we will create a new .Strings file. For that, right-click on your Project -> New File -> search for 'strings' -> Select Strings File -> name the file as Localizable.strings -> Create.
- Now, go to File Inspector again and under Localization, select all the languages that you had added.
- Once the Strings file is created, click on the Localizable.strings file and in the File Inspector, click on the Localize button.
- On clicking the Localize button, a similar popup will appear. Click on Localize.
- Now, go to File Inspector again and under Localization, select all the languages that you had added.
- Now create a UI in Main.storyboard. In my project, I have used a UIPickerView to select a language and based on the language selected, I'm displaying title and data.
- After you create your UI, go to Localizable files and create some keys and assign the values to the keys that you will be displaying on your UI.

- NOTE
Use the same keys in all the Localizable.strings files.

Refer the below code snippets and add the sentences that you will be displaying on your UI in a key-value type.
