### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by dfallow** [FUKA-INNOVATIONS/Safeye#29]
- [x] Create new project
- [x] Design
- [x] Implement in project

**Comment by FUKA-INNOVATIONS** [comment]
Initially done

**Comment by FUKA-INNOVATIONS** [comment]
https://docs.google.com/document/d/1TzG-ahzmiQvIkFV_AvI-KEdZzzrElEWuVnS10nHFv04/edit

**Comment by FUKA-INNOVATIONS** [comment]
Initial (not complete) folder structure with empty files.
Merged
