### ISSUE TITLE
Activate panic mode functionality

### ISSUE THREAD

**Issue by gintaresaali** [FUKA-INNOVATIONS/Safeye#41]
Activate Panic Mode:
- [x] Toggle Panic Mode
- [x] Send notification to Trusted contacts (after #39 is ready)
- [ ] Popup warning after pressing button
- [ ] Send loud alert to trusted contacts

Disable Panic Mode:
- [x] Disable panic mode
- [x] Send notification to Trusted contacts (after #39 is ready)
- [ ] Popup confirmation

**Comment by FUKA-INNOVATIONS** [comment]
toggling panic mode and disabling panic mode is already implemented, This is also updated in the database and trusted contacts get  released time updates.
