### ISSUE TITLE
View Profile of trusted contact

### ISSUE THREAD

**Issue by FUKA-INNOVATIONS** [FUKA-INNOVATIONS/Safeye#88]
- [x] Show profile details
- [x] Show avatar
- [x] Show names in connection view
       - [x] connections
       - [ ] pending reqs
       - [ ] sent reqs

**Comment by gintaresaali** [comment]
There's bugs atm, as mentioned in the meeting. You have to first go to Profile View and then to Connections View. Going back to Profile View from there will crash the app.
